spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.driver
    url: jdbc:mysql://localhost:3306/rest-with-spring-boot-training?useTimezone=true&serverTimzone=UTC
    username: root
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false
      